CC=g++
CFLAGS=-std=c++11 -Wall

all: question1 question2 question3

question1: question_1.cpp
	$(CC) $(CFLAGS) question_1.cpp -o question1

question2: question_2.cpp
	$(CC) $(CFLAGS) question_2.cpp -o question2

question3: question_3.cpp
	$(CC) $(CFLAGS) question_3.cpp -o question3

clean:
	rm -f question1 question2 question3 output.txt
